version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: travel-postgres
    environment:
      POSTGRES_DB: travel_db
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - travel-network

volumes:
  postgres_data:

networks:
  travel-network:
    driver: bridge
